# Generated by Django 3.2.25 on 2024-05-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
